Homework2

In [27]:
def determinant(m):
    if len(m) <= 0:
        return None
    if len(m) == 1:
        return m[0][0] 
    else:
        ans = 0
    for i in range(len(m)):
        n = [[row[a]
    for a in range(len(m))
        if a != i] 
    for row in m[1:]] 
        if i % 2 == 0:
            ans += m[0][i] * determinant(n)
        else:
            ans -= m[0][i] * determinant(n)
    return ans

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 14)

In [22]:
import numpy as np

In [23]:
n= 3
np.random.seed(0)
A= np.random.randint(-5,5,size=(n,n))
print(f'A= \n{A}')

A= 
[[ 0 -5 -2]
 [-2  2  4]
 [-2  0 -3]]


In [24]:
determinant(A)

62