Homework2

In [40]:
import numpy as np

In [41]:
def determinant(m):
    if len(m) <= 0:
        return None
    if len(m) == 1:
        return m[0][0] 
    else:
        ans = 0
    for i in range(len(m)):
        n = [[row[a]
    for a in range(len(m))
        if a != i] 
    for row in m[1:]] 
        if i % 2 == 0:
            ans += m[0][i] * determinant(n)
        else:
            ans -= m[0][i] * determinant(n)
    return ans

In [42]:
n= 5
np.random.seed(0)
A= np.random.randint(-5,5,size=(n,n))
print(f'A= \n{A}')

A= 
[[ 0 -5 -2 -2  2]
 [ 4 -2  0 -3 -1]
 [ 2  1  3  3 -4]
 [ 1  2  2  3 -4]
 [ 0  4  3  4 -1]]


In [43]:
determinant(A)

112