In [2]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [6]:
b = np.array([3,17])
b

array([ 3, 17])

In [7]:
x = la.solve(A, b)
x
#ANS

array([11., -4.])